FORMAT: 1A

# meetupDemoService
    
    Let's get you started with your own API 

### Health check [/healthcheck]

## HeartBeat [GET]
+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Credentials: true

    + Body

            {
                "Result": "Your service running normally."
            }

+ Response 404 (application/json)

    + Headers

            Access-Control-Allow-Credentials: true

    + Body

            {
                "Result": "Srevice is not running right now"
            }

## Data structures

### Question
- question: What's your favourite language? (string)
- `published_at`: `2017-06-17` (string)
- `is_published`: true (boolean)
- choices (array[Choice])

### Choice
- choice: java (string)
- url (string)
- votes:100 (number)

## Group Question management
  Collection of services which supports question functionality.
  
## Question [/questions]

### Get all questions [GET]

+ Response 200 (application/json)

    + Attributes(array[Question])

### Add new question [POST]

+ request

    + Attributes(Question)

+ Response 202 (application/json)

    + Attributes(Question)

## Question detail [/questions/{question_id}]

### View a question detail [GET]

+ Parameters

    + `question_id`: 1 (required, number) - Question identification number.

+ Response 200 (application/json)

    + Attributes(Question)