FORMAT: 1A

# meetupDemoService
    
    Let's get you started with your own API 

## HeartBeat [GET /]

+ Response 200 (plain/text)
        
        Your service is running normally.

## Data structures
### Question
- question: What's your favourite language? (string)
- `published_at`: `2017-06-17` (string)
- `is_published`: true (boolean)
- choices (array[Choice])

### Choice
- choice: java (string)
- url (string)
- votes (number)

## Group Question

## Question list [/questions]

### Questions [GET]

+ Response 200 (application/json)

    + Attributes(array[Question])

## Question detail [/questions/{question_id}]

+ Parameters
    + `question_id`: 1 (required, number) - ID

### View a question detail [GET]

+ Response 200 (application/json)

    + Attributes(Question)